'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class data_pribadi

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''Logout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Logout As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NAMA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NAMA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NAMARequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NAMARequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''NISN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NISN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''nisnR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nisnR As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''NIK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NIK As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NIKRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NIKRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''KP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents KP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''KPRegex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents KPRegex As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''Calendar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Calendar1 As Global.System.Web.UI.WebControls.Calendar

    '''<summary>
    '''NHP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NHP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NHPRegex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NHPRegex As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''JK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JK As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''JKRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JKRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ThL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ThLRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThLRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''AGAMA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AGAMA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AGAMARequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AGAMARequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''NS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NSRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NSRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ALAMAT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ALAMAT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ALAMATRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ALAMATRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''NPSN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NPSN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NPSNR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NPSNR As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''JURUSAN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JURUSAN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''JURUSANRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JURUSANRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''AS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents [AS] As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ASRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''INPUT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents INPUT As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''inputt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputt As Global.System.Web.UI.WebControls.Button
End Class
